import 'package:get/get.dart';


class AppTranslation extends Translations {
  Map<String, Map<String, String>> get keys => {
    'en': {
      'Get Started': 'Get Started',
      "Your key to a new Home.": "Your key to a new Home.",
      'Phone Number:': 'Phone Number:',
      "Enter Your Phone Number": "Enter Your Phone Number",
      'Password:': 'Password:',
      'Enter Your Password': 'Enter Your Password',
      'Login':'Login',
      "Don't have an account?":"Don't have an account?",
      'Signup':'Signup',
      'First Name:':'First Name:',
      'Enter Your First Name':'Enter Your First Name',
      'Last Name:':'Last Name:',
      'Enter Your Last Name':'Enter Your Last Name',
      'Date Of Birth:':'Date Of Birth:',
      "Day":"Day",
      "Month":"Month",
      "Jan":"Jan",
      "Feb":'Feb',
      "Mar":'Mar',
      "Apr":'Apr',
      "May":'May',
      "Jun":"Jun",
      "Jul":"Jul",
      "Aug":'Aug',
      "Sep":"Sep",
      "Oct":'Oct',
      "Nov":"Nov",
      "Dec":"Dec",
      "Year":"Year",
      'Add Your ID Photo:':'Add Your ID Photo:',
      'Upload Your ID':'Upload Your ID',
      'Upload':'Upload',
      'Change':'Change',
      'Delete':'Delete',
      'Confirm Password:':'Confirm Password:',
      'I am an owner':'I am an owner',
      'Please Enter Phone Number':'Please Enter Phone Number',
      'Phone number must contain only digits':'Phone number must contain only digits',
      'Phone number must be exactly 10 digits':'Phone number must be exactly 10 digits',
      'Phone number must start with 09':'Phone number must start with 09',
      'Please Enter The Password':'Please Enter The Password',
      'Password must be at least 8 characters long':'Password must be at least 8 characters long',
      'Please Enter Your Name':'Please Enter Your First Name',
      'Only letters are allowed':'Only letters are allowed',
      'Name must be at least 2 characters':'Name must be at least 2 characters',
      'Please confirm your password':'Please confirm your password',
      'Passwords do not match':'Passwords do not match',
      'Please select your full date of birth':'Please select your full date of birth',
      'You must be at least 18 years old':'You must be at least 18 years old',

    },
    'ar': {
      'Get Started': 'ابدأ',
      "Your key to a new Home.": 'مفتاحك لبيت جديد.',
      'Phone Number:': 'رقم الهاتف:',
      "Enter Your Phone Number": 'ادخل رقم هاتفك',
      'Password:': 'كلمة المرور',
      'Enter Your Password': 'ادخل كلمة المرور لحسابك',
      'Login':'تسجيل الدخول',
      "Don't have an account?":'لا تمتلك حساب؟',
      'Signup':'انشىء حساب',
      'First Name:':'الاسم الأول:',
      'Enter Your First Name':'ادخل اسمك الأول',
      'Last Name:':'الأسم الأخير:',
      'Enter Your Last Name':"ادخل أسمك الأخير",
      'Date Of Birth:': 'تاريخ الميلاد:',
      "Day":'اليوم',
      "Month":"الشهر",
      "Jan":"كانون الثاني",
      "Feb":'شباط',
      "Mar":'اّذار',
      "Apr":'نيسان',
      "May":'أيار',
      "Jun":"حزيران",
      "Jul":"نموز",
      "Aug":'اّب',
      "Sep":"أيلول",
      "Oct":'تشرين الأول',
      "Nov":"تشرين الثاني",
      "Dec":"كانون الأول",
      "Year":"السنة",
      'Add Your ID Photo:':'اضف صورة الهوية:',
      'Upload Your ID':'اضف صورة الهوية',
      'Upload':"اضافة",
      'Change':'تغيير',
      'Delete':'مسح',
      'Confirm Password:':'أكد كلمة المرور',
      'I am an owner':'أنا مالك منزل',
      'Please Enter Phone Number':'الرجاء ادخال رقم الهاتف',
      'Phone number must contain only digits':"ادخل ارقام فقط",
      'Phone number must be exactly 10 digits':'الرقم يجب ان يكون 10 خانات',
      'Phone number must start with 09':'رقم الهاتف يجب ان يبدأ ب 09',
      'Please Enter The Password':'الرجاء كتابة كلمة السر',
      'Password must be at least 8 characters long':'يجب ان تكون كلمة السر اكثر من 8 محارف',
      'Please Enter Your Name':'ادخل اسمك ',
      'Only letters are allowed':'ادخل فقط احرف',
      'Name must be at least 2 characters':'الأسم يجب ان يكون اكثر من حرفين',
      'Please confirm your password':'الرجاء تأكيد كلمة السر',
      'Passwords do not match':'كلمة السر غير متوافقة',
      'Please select your full date of birth':'الرجاء اختيار تاريخ ميلادك كامل',
      'You must be at least 18 years old':"يجب ان تكون اكبر من 18 عام",


    },
  };
}
